// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Even.Persistence.Sql")]
[assembly: AssemblyProductAttribute("Even")]
[assembly: AssemblyDescriptionAttribute("An event sourcing framework on top of Akka.NET")]
