// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Even.Sample")]
[assembly: AssemblyProductAttribute("Even")]
[assembly: AssemblyDescriptionAttribute("An event sourcing framework on top of Akka.NET")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
