// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Even")]
[assembly: AssemblyProductAttribute("Even")]
[assembly: AssemblyDescriptionAttribute("An event sourcing framework on top of Akka.NET")]
[assembly: InternalsVisibleTo("Even.Tests")]
